server:
  port: 8003
mybatis:
  type-aliases-package: com.edc.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.60.202:3306/db03?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: longlong

eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
#      defaultZone: http://localhost:7001/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: provider-8003

info:
  app.name: derer
  company.name: dddd